### ISSUE TITLE
Foreign key being deleted from associated fetch

### ISSUE THREAD

**Issue by mark-lester** [dchester/epilogue#104]
/Routes/1/Trips drops the RouteId, which is 1 of course so it's not a show stopper for me to have to put it back. Is there is a way of asking for it not to be removed ?, 
 
I thought I had the block of code that was doing that at the end of list.js but I remarked it out and RouteId was still missing.

**Comment by mark-lester** [comment]
So there's two places where this is done, once at the bottom of list.js, but then again, with no attempt at qualification, at the bottom of has-many. I've remarked both out pending thought on how to configure, but do we need both of these ?.

**Comment by mbroadst** [comment]
@mark-lester hey, it would be helpful if you could link to the code you're referring to in the comments to help me track through this with you. Are you referring to [this](https://github.com/dchester/epilogue/blob/master/lib/associations/has-many.js#L20) here? It does indeed look like that is double effort. If you pull it out does it break any tests? I'd say go ahead and remove it otherwise

A little bit of a caveat emptor here: the auto association code was based on an original punt I was working on when I still needed this module for a larger project. It was then completed by another user in collaboration wit me, but it is certainly missing functionality. 

As far as the initial question, the primary keys should not be stripped by default, though you may have discovered why they are in your case here already.

**Comment by mark-lester** [comment]
yes thats the line, I thought it was also going on here  https://github.com/dchester/epilogue/blob/master/lib/Controllers/list.js#L141 but I dont have any includes of course, so that wasnt getting called anyway.

**Comment by mbroadst** [comment]
@mark-lester should be fixed in https://github.com/dchester/epilogue/commit/8d31e62c8e9434bd73b7a0d2cd6bb0cd11fe5632, would appreciate if you could check that out

**Comment by mark-lester** [comment]
@mbroadst many thanks indeed, I will test first thing in the morning.

**Comment by mark-lester** [comment]
yes that worked for me many thanks.
