### ISSUE TITLE
Create returns object but includes excludedAttributes?

### ISSUE THREAD

**Issue by hurricane766** [dchester/epilogue#116]
Here is my user model and resource definition:

	var User = config.db.define('User', {
		email: { type: Sequelize.STRING(255), unique: true, allowNull: false },
		password: { type: Sequelize.STRING(64), allowNull: false},
		salt: { type: Sequelize.STRING(64), allowNull: false},
		firstName: { type: Sequelize.STRING(64), allowNull: false},
		lastName: { type: Sequelize.STRING(64), allowNull: false},
		gender: Sequelize.CHAR(1),
		country: Sequelize.STRING(64)
	});

    var userResource = epilogue.resource({
		model: config.db.models.User,
		endpoints: ['/user', '/user/:id'],
		excludeAttributes: ['password', 'salt', 'createdAt', 'updatedAt'],
		actions: ['create', 'read', 'update']
	});

`read`ing the resource will return:
{"id":1,"email":"Serena72@hotmail.com","firstName":"Jovany","lastName":"Gerhold","gender":null,"country":null}

`create`ing the resource will return:
{"id":1,"email":"Serena72@hotmail.com","password":"_1bBwqH_0LQVyrl","salt":"b2d29b7d-5a4a-4030-a160-d60590a59908","firstName":"Jovany","lastName":"Gerhold","gender":null,"country":null,"createdAt":"2015-11-08T16:14:02.000Z","updatedAt":"2015-11-08T16:14:02.000Z"}

I rather not to have password hashes and salts available at anytime. I realize the workaround would be to remove those fields myself, but isn't that the point of excluded fields?

**Comment by philotas** [comment]
had the same problem. 

Since I did the user creation myself I provided a milestone for write before. created the user and then removed the attributes from the context.instance

```javascript
context.instance = registeredUser;
delete context.instance.dataValues.hash;
delete context.instance.dataValues.salt;
context.skip(); // skip creation of user
```

you might do the same thing in write after

Anyhow, `excludeAttributes` is something that should be also applied to the response upon creation.

**Comment by mbroadst** [comment]
unfortunately the best we can do is remove the data values, since we're just calling `reload` on an instance that was already preloaded with the private data. I've fixed this in https://github.com/dchester/epilogue/commit/840d6cdc6ea1b58392e5de04d43629f55f37ade5

Additionally, it appears that we're doing double bookkeeping with the excludeAttributes as sequelize allows passing in `{ attributes: { include: ['some', 'attrs'], exclude: ['other'] } }`. We do depend on attributes being a single list of data in a few places which is why it didn't make it into this commit, but it would be a cool project if someone was interested in implementing it

**Comment by hurricane766** [comment]
Thank you!
