### ISSUE TITLE
Support versioning

### ISSUE THREAD

**Issue by ilaif** [dchester/epilogue#145]
Hey guys,

I've noticed that there's no documentation or any reference inside the code for route versioning.

In restify the convention is to add a header 'Accept-Version' with the version so restify can parse that and route accordingly.

Did I miss anything?

Thanks,
Ilai

**Comment by mbroadst** [comment]
@ilaif yeah since the module originally targeted express explicitly, there were no such considerations. I added restify support (i.e. testing against restify, as well as that bug you noted in the other ticket), but have not done anything regarding versioning. This would be another nice item for someone to pick up for implementation, but as I said I've taken a back seat into maintenance/mediation mode on this module since I don't actively use it for any projects currently.

**Comment by ilaif** [comment]
@mbroadst Ok that's totally fine. Can you give a direction where I should look? Basically what I understand is that when you define a resource you should also pass the version and then it should be injected in the route definition in restify.

**Comment by mbroadst** [comment]
@ilaif to be honest I'm not sure there's a quick and dirty way about doing it. From the docs it looks like the route definition needs to be changed to `{ path: PATH, version: 'someVersion' }`, so you'd need to change epilogue where it mounts the endpoints in the base controller [here](https://github.com/dchester/epilogue/blob/master/lib/Controllers/base.js#L67). You'd have to think about what the user api for that might be, perhaps if just a `version` parameter is passed into the resource creation call?

You might also just be able to implement this as a milestone on the resource, something like this might work:
```
myResource.all.send.before((req, res, context) => {
   res.setHeader('Accept-Version', 'whatever');
   return context.continue();
});
``

As for handling multiple versions, that would be another difficult/interesting case..

**Comment by marianzange** [comment]
I have the same use case. I need to support versioned routes on my restify API. I just quickly threw together a very dirty proof-of-concept that allows adding a 'version' option when creating the epilogue resource (like @mbroadst suggested above): 

```javascript
var userResource = epilogue.resource({
  model: models.User,
  endpoints: ['/users', '/users/:id'],
  version: '2.0.0'
});
```
I'm fairly new to the whole NodeJS party, so if anyone wants to pick this up, feel free. Otherwise I might look into properly implementing it myself in a couple of weeks. Here's the POC: https://github.com/marianzange/epilogue/commit/e291581188e815ef2a1e113a4a2f6220c67458f1
