### ISSUE TITLE
Body parser is missing, Epilogue fails on a bare Express 4.x app without it

### ISSUE THREAD

**Issue by bradisbell** [dchester/epilogue#50]
When Epilogue is used in an application that doesn't already use body-parser, it fails to process JSON out of a POST body causing all fields to be undefined.

I worked around this in my application by adding it at the application level, but I believe this should be added to Epilogue directly so that Epilogue can stand alone.  Example:  http://stackoverflow.com/a/27855234/362536

In addition, while tracking down this issue I spent a good amount of time assuming my POST body was incorrect in some way.  I found that there was no example outside of the unit tests for what to POST to Epilogue.  Perhaps the README should have a basic example?

**Comment by mbroadst** [comment]
@bradisbell yeah perhaps there should be some explicit documentation about the requirements on the server you use. I don't think that including body-parser as a dependency to epilogue is the right answer since I'm keen on being able to support express as well as restify (the idea being that setting up your web server is a task left to the user of epilogue). 

As for examples of POST data, I think it's a good idea to provide more in depth examples of the types of data epilogue expects. The integration tests show this to a certain extent, but that's not always easiest for users of this module to find on their own. We're discussing some documentation related questions on the promise migration PR, so I'll make sure to keep this in mind with whatever approach we end up taking.

**Comment by bradisbell** [comment]
Sounds like a plan.  Thanks for the fast reply.
