### ISSUE TITLE
Is this module using Express or Restify?

### ISSUE THREAD

**Issue by silvioprog** [dchester/epilogue#82]
Hello,

I'm newbie in Node.js and RESTful APIs using this project, but your READ says:

> Create flexible REST endpoints and controllers from Sequelize models in your **Express** app in Node.

However, the main demo uses **Restify**:

```node
var Sequelize = require('sequelize'),
    restify = require('restify'), // << here!
    epilogue = require('epilogue');
...
```

So, is this module using Express or Restify? =/

Thank you!

**Comment by mbroadst** [comment]
@silvioprog this module uses neither express OR restify :smile: Instead the choice is up to you based on what the requirements of your project are. The examples on the main page use restify because that's what I use, so it was easier for me to put up examples on the fly from that.

You'll notice that the automated tests test against restify and express to verify that this works. Generally, using the examples in the README you can simple replace the "app" variable passed into epilogue with your express app/server object (whatever you named it)

**Comment by silvioprog** [comment]
Very nice. =)

You could update the demo adding a short comment like "`// or Express`" in the app declaration.

Thanks a lot for this information, and nice job in this framework, it seems very promissor! :sunglasses:

**Comment by mbroadst** [comment]
@silvioprog by all means, if you submit a PR for that we'll put it right up :smile:

**Comment by bixibu** [comment]
Docs is not clear on the use of restify/express. Hopefully I searched on closed issues and found this post, but I nearly closed tab when seeing restify. I think you should rephrase a little all that ;)

**Comment by mbroadst** [comment]
I could never have imagined this would have caused so much confusion, hopefully https://github.com/dchester/epilogue/commit/5d2aae3064271123116e8498def3c953b15c3170 will clear it up once and for all.
