### ISSUE TITLE
Validating JSON output before sending ?

### ISSUE THREAD

**Issue by jscti** [dchester/epilogue#84]
Hello

I'm having a few problems when trying to validate the JSON output. How would you do that for a specific route (LIST) ?

I tried to add my validation routine (using ajv) in ``myApi.list.data.after(function(){});`` without success :
- should I be doing this in ``list.data.after`` or ``list.send.before`` ?
- is it normal that ``list.data.after()`` is never called but ``list.data()`` is called (I though the logic was <entity>.<controller>.<milestone>.<before|action|after>) ?
- how can I have access to the generated JSON ?

Thanks for you help and this awesome module !

**Comment by mbroadst** [comment]
@bixibu this is sort of a weak point in the design unfortunately. Certain controllers behave differently, so your assumptions are not correct for the ListController. Generally, the json encoding actually occurs as part of the default send milestone: https://github.com/dchester/epilogue/blob/master/lib/Controllers/base.js#L67.

The 'data' milestone is not actually defined for any of the controllers by default, but you can assign a 'data' step in order to manipulate (or check) the data. That's probably where I would put my checks. As for why the "before" and "after" aren't called, well that's because there is nothing for there to be before or after! You need to define a data milestone, and then if you want to do something before that you can define a `list.data.before`

**Comment by mbroadst** [comment]
In case that wasn't so clear above: if you want access to the generated JSON, we don't prepare that explicitly before sending a `res.json` in the send step. You can validate the `context.instance` at any point in your workflow, or you could actually set `context.instance` to the JSON yourself on a `list.send.before` step maybe?
