### ISSUE TITLE
Error formating / Docs

### ISSUE THREAD

**Issue by jscti** [dchester/epilogue#94]
I'm trying to follow docs/Milestones.md in order to change the error output of my APIs.

A few questions :
1) is there a way to globally update the Error JSON output ({message, errors}) or is it only possible per-action ?
2) Secondly : should the following code work ? If yes, do you have a clue why it doesn't ? 

```javascript
var resource = epilogue.resource({
    model: models.test,
    endpoints: ['/test', '/test/:id']
});

resource.create.error = function(req, res, error) {
    res.status(500);
    res.json({message: 'Custom error'});
};

var resourceMiddlewares = {
    create: {
        write: {
            before: function(req, res, context) {
                throw new epilogue.Errors.BadRequestError("just fail please");
                return context.continue();
            }
        }
    }
};
```

3) I struggled to have a working "create.write.before" hook, the docs aren't clear : 
```javascript
var resource = epilogue.resource({
    model: models.test,
    endpoints: ['/test', '/test/:id']
});
resource.create.write.before(function() {[...]}); //doesn't work
resource.use({create:{write:{before: function() {[...]}}}}) //works but not documented
```

Not sure If I understood all well though :o

Thanks

**Comment by mbroadst** [comment]
Hey,

1) you should be able to override/monkeypatch this: https://github.com/dchester/epilogue/blob/master/lib/Controllers/base.js#L59. All error paths should be using that to send an error, and if they aren't, then we should fix that :)

2) That looks like you tried answer 1 and it didn't work. I assume what you expected to see was a 500 error with a 'Custom error' message? What did you see instead?

3) Yes that should work, it was the original form of milestones before middleware was introduced. What did you experience? The method wasn't called at all? It wasn't called when you expected it to? Generally if the middleware version works, then the "regular" milestone version works, as the middleware just applies itself using the milestone approach. Are you sure you don't have some other milestone function blocking the operation you're expecting?

**Comment by jscti** [comment]
Hi

1) yep I saw this but hoped I hadn't to fork it :)

2) not really tried your answer 1 as I didn't modifiy epilogue source code, I was in my module trying to use your documented APIs in order to add custom formating to epilogue errors. The error I saw was the standard epilogue one with message = "just fail please". 

3) method wasn't called at all and I have nothing else related to epilogue outside of this module of mine

Thanks

**Comment by mbroadst** [comment]
@jscti hey sorry for the delay here. I've added some new tests and corrected a bug in the master branch. To answer your original questions properly:

1) This was a stupid error on my part. It's not exactly super user friendly but the way to do this is to call `myResource.controllers.[create | read | update | delete | list].error = function(req, res, err) {}`, you can find an example of this here: https://github.com/dchester/epilogue/blob/master/tests/resource/resource.test.js#L134

2) No the following shouldn't work, see above. I would be willing to discuss adding a parameter to resource construction that overrides the default error handler maybe?

3) I'm not sure what's going on here for you without seeing more code. As stated previously the middleware (`resource.use`) is actually mapping directly to that "explicit" style. This works for me, and I've added two tests in the code to prove it starting here: https://github.com/dchester/epilogue/blob/master/tests/milestones/milestones.test.js#L569

You _might_ have a bug because you throw an error and then `return context.continue()` though that should never be reached. I've also corrected one bug (seemingly unrelated to your exact problems) where a user could call `context.error` with a proper EpilogueError instance.

Hope this helps!

**Comment by mbroadst** [comment]
@jscti did that help?

**Comment by syedf** [comment]
Hey @mbroadst , Thanks for this, but docs don't mention that you have to override `resource.controller.actions.error` (it just says `resource.actions.error` ). can you change it? (or maybe i can change and send a PR)

**Comment by mbroadst** [comment]
@syedf sure PRs are more than welcome!

**Comment by syedf** [comment]
how do i send PR's, it says i don't have permission for that action

**Comment by mbroadst** [comment]
@syedf you will need to fork this repo, and push the changes to a branch on your fork. Once you do that, github will make a convenient little button for you to open a PR over here. This should help: https://help.github.com/articles/using-pull-requests/

**Comment by syedf** [comment]
@mbroadst  Thanks for the amazingly fast response! Sorry i am new to this, i couldn't push the changes using the github app, so i edited it on the web itself and have submitted one pull request.

**Comment by mbroadst** [comment]
you got it :) thanks for the help

**Comment by syedf** [comment]
Thank you :)
